import type { Metadata } from "next";
import { Inter } from "next/font/google";           // فونت Inter اضافه شد
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";         // برای مدیریت dark mode
import { cn } from "@/utils/cn";                     // اگر نداری، می‌تونی حذف کنی یا بسازی
import { NotificationProvider } from '@/components/ui/notification-provider';
import { Toaster } from '@/components/ui/toast';
// فونت Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// فونت‌های Geist که قبلاً داشتی
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={cn(
          inter.variable,          // Inter به عنوان فونت sans اصلی
          geistSans.variable,      // Geist Sans
          geistMono.variable,      // Geist Mono
          "antialiased"
        )}
      >
        <ThemeProvider
          attribute="data-theme"          // مهم برای Tailwind v4
          defaultTheme="system"           // پیش‌فرض: دنبال تنظیمات سیستم
          enableSystem                    // فعال کردن تشخیص سیستم
          enableColorScheme               // اختیاری اما مفید
        >
          {children}
          <NotificationProvider />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}